apiVersion: v1
kind: Service
metadata:
  name: sample-service
  labels:
    app: sample-app
spec:
  selector:
    app: sample-app
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  type: LoadBalancer
